/**
 */
package dmss_pa_01.provider;

import dmss_pa_01.util.Dmss_pa_01AdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITableItemLabelProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Dmss_pa_01ItemProviderAdapterFactory extends Dmss_pa_01AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Dmss_pa_01ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(ITableItemLabelProvider.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Universidad} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UniversidadItemProvider universidadItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Universidad}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUniversidadAdapter() {
		if (universidadItemProvider == null) {
			universidadItemProvider = new UniversidadItemProvider(this);
		}

		return universidadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.TituloUniversitario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TituloUniversitarioItemProvider tituloUniversitarioItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.TituloUniversitario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTituloUniversitarioAdapter() {
		if (tituloUniversitarioItemProvider == null) {
			tituloUniversitarioItemProvider = new TituloUniversitarioItemProvider(this);
		}

		return tituloUniversitarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Asignatura} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AsignaturaItemProvider asignaturaItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Asignatura}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAsignaturaAdapter() {
		if (asignaturaItemProvider == null) {
			asignaturaItemProvider = new AsignaturaItemProvider(this);
		}

		return asignaturaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Profesor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProfesorItemProvider profesorItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Profesor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProfesorAdapter() {
		if (profesorItemProvider == null) {
			profesorItemProvider = new ProfesorItemProvider(this);
		}

		return profesorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Alumno} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AlumnoItemProvider alumnoItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Alumno}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAlumnoAdapter() {
		if (alumnoItemProvider == null) {
			alumnoItemProvider = new AlumnoItemProvider(this);
		}

		return alumnoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Bloque} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BloqueItemProvider bloqueItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Bloque}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBloqueAdapter() {
		if (bloqueItemProvider == null) {
			bloqueItemProvider = new BloqueItemProvider(this);
		}

		return bloqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Encuesta} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EncuestaItemProvider encuestaItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Encuesta}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEncuestaAdapter() {
		if (encuestaItemProvider == null) {
			encuestaItemProvider = new EncuestaItemProvider(this);
		}

		return encuestaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Consulta} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConsultaItemProvider consultaItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Consulta}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConsultaAdapter() {
		if (consultaItemProvider == null) {
			consultaItemProvider = new ConsultaItemProvider(this);
		}

		return consultaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Tarea} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaItemProvider tareaItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Tarea}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTareaAdapter() {
		if (tareaItemProvider == null) {
			tareaItemProvider = new TareaItemProvider(this);
		}

		return tareaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.ENLACEURL} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ENLACEURLItemProvider enlaceurlItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.ENLACEURL}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createENLACEURLAdapter() {
		if (enlaceurlItemProvider == null) {
			enlaceurlItemProvider = new ENLACEURLItemProvider(this);
		}

		return enlaceurlItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Foro} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForoItemProvider foroItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Foro}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForoAdapter() {
		if (foroItemProvider == null) {
			foroItemProvider = new ForoItemProvider(this);
		}

		return foroItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Recurso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecursoItemProvider recursoItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Recurso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecursoAdapter() {
		if (recursoItemProvider == null) {
			recursoItemProvider = new RecursoItemProvider(this);
		}

		return recursoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.GrupoTrabajo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GrupoTrabajoItemProvider grupoTrabajoItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.GrupoTrabajo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGrupoTrabajoAdapter() {
		if (grupoTrabajoItemProvider == null) {
			grupoTrabajoItemProvider = new GrupoTrabajoItemProvider(this);
		}

		return grupoTrabajoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Pregunta} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PreguntaItemProvider preguntaItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Pregunta}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPreguntaAdapter() {
		if (preguntaItemProvider == null) {
			preguntaItemProvider = new PreguntaItemProvider(this);
		}

		return preguntaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Respuesta} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RespuestaItemProvider respuestaItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Respuesta}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRespuestaAdapter() {
		if (respuestaItemProvider == null) {
			respuestaItemProvider = new RespuestaItemProvider(this);
		}

		return respuestaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link dmss_pa_01.Root} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RootItemProvider rootItemProvider;

	/**
	 * This creates an adapter for a {@link dmss_pa_01.Root}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRootAdapter() {
		if (rootItemProvider == null) {
			rootItemProvider = new RootItemProvider(this);
		}

		return rootItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (universidadItemProvider != null) universidadItemProvider.dispose();
		if (tituloUniversitarioItemProvider != null) tituloUniversitarioItemProvider.dispose();
		if (asignaturaItemProvider != null) asignaturaItemProvider.dispose();
		if (profesorItemProvider != null) profesorItemProvider.dispose();
		if (alumnoItemProvider != null) alumnoItemProvider.dispose();
		if (bloqueItemProvider != null) bloqueItemProvider.dispose();
		if (encuestaItemProvider != null) encuestaItemProvider.dispose();
		if (consultaItemProvider != null) consultaItemProvider.dispose();
		if (tareaItemProvider != null) tareaItemProvider.dispose();
		if (enlaceurlItemProvider != null) enlaceurlItemProvider.dispose();
		if (foroItemProvider != null) foroItemProvider.dispose();
		if (recursoItemProvider != null) recursoItemProvider.dispose();
		if (grupoTrabajoItemProvider != null) grupoTrabajoItemProvider.dispose();
		if (preguntaItemProvider != null) preguntaItemProvider.dispose();
		if (respuestaItemProvider != null) respuestaItemProvider.dispose();
		if (rootItemProvider != null) rootItemProvider.dispose();
	}

}
